apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-dash-app
  name: sample-dash-app
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sample-dash-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-dash-app
    spec:
      containers:
      - image: reusin/sample-dash-app:1.0
        imagePullPolicy: IfNotPresent
        name: sample-dash-app
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
