apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-dash-app
  name: sample-dash-app
spec:
  ports:
  - nodePort: 32101
    port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: sample-dash-app
  type: NodePort
status:
  loadBalancer: {}
